/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Outbox {
  createdAt: Generated<Timestamp>;
  data: Json;
  id: Generated<string>;
  processedAt: Timestamp | null;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  avatarId: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  firstName: string | null;
  githubId: string | null;
  googleId: string | null;
  hashedPassword: string | null;
  id: Generated<string>;
  isBanned: Generated<boolean>;
  isVerified: Generated<boolean>;
  lastName: string | null;
  role: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Workspace {
  city: string | null;
  country: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  postalCode: string | null;
  street: string | null;
  streetNumber: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  outbox: Outbox;
  users: Users;
  workspace: Workspace;
}
